method: random
metric:
  name: loss
  goal: minimize
parameters:
  train_ratio: 
    value: 0.9
  batch_size:
    value: 128
  lr:
    value: 0.003
  epochs:
    value: 200
  n_feat_dim: 
    value: 4
  embed_dim: 
    values: [16,32,64,96,128]
  hidden_dim: 
    values: [16,32,64,96,128]
  num_encoder_blocks: 
    values: [4,8,16]
  num_attn_heads: 
    values : [4,8,16]
  dropout_gen:
    value: 0.2
  SDE:
    values : ["VE","VP"]
  sigma_max: 
    values: [1.0,5.0,10.0]
  sigma_min: 
    values: [0.0001,0.0003,0.001,0.00003]
  sampler_steps:
    values: [50,100,500,1000]
  n_showers_2_gen: 
    value: 10000
  correction_steps:
    values : [10,25,50]
